package no.nav.vedtak.felles.integrasjon.sak;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.soap.SOAPFactory;
import javax.xml.soap.SOAPFault;
import javax.xml.ws.soap.SOAPFaultException;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import no.nav.tjeneste.virksomhet.sak.v1.binding.SakV1;
import no.nav.tjeneste.virksomhet.sak.v1.meldinger.FinnSakRequest;
import no.nav.vedtak.exception.IntegrasjonException;

public class SakConsumerTest {

    private SakConsumer consumer;

    @Rule
    public ExpectedException expectedException = ExpectedException.none();

    private SakV1 mockWebservice = mock(SakV1.class);

    @Before
    public void setUp() {
        consumer = new SakConsumerImpl(mockWebservice);
    }

    @Test
    public void skalKasteIntegrasjonsfeilNÃ¥rWebserviceSenderSoapFault() throws Exception {
        when(mockWebservice.finnSak(any(FinnSakRequest.class))).thenThrow(opprettSOAPFaultException("feil"));

        expectedException.expect(IntegrasjonException.class);
        expectedException.expectMessage("FP-942048");

        consumer.finnSak(mock(FinnSakRequest.class));
    }

    private SOAPFaultException opprettSOAPFaultException(String faultString) throws SOAPException {
        SOAPFault fault = SOAPFactory.newInstance().createFault();
        fault.setFaultString(faultString);
        fault.setFaultCode(new QName("local"));
        return new SOAPFaultException(fault);
    }
}
